// <auto-generated />
namespace Diplom_WebSite_Taras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dateremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dateremove));
        
        string IMigrationMetadata.Id
        {
            get { return "201808141943233_Date remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
