// <auto-generated />
namespace Diplom_WebSite_Taras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addcartandorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcartandorders));
        
        string IMigrationMetadata.Id
        {
            get { return "201808031839538_Add cart and orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
