// <auto-generated />
namespace Diplom_WebSite_Taras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adduserorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adduserorders));
        
        string IMigrationMetadata.Id
        {
            get { return "201808290934215_Add user orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
