// <auto-generated />
namespace Diplom_WebSite_Taras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Checkout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Checkout));
        
        string IMigrationMetadata.Id
        {
            get { return "201808061916578_Checkout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
